version: "3.7"

services:
  app:
    image: 'docker-spring-boot-mysql:latest'
    build:
      context: ..
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/projectzero
      - SPRING_DATASOURCE_USERNAME=projectzero
      - SPRING_DATASOURCE_PASSWORD=projectzero
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'mysql:latest'
    container_name: db
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=projectzero
      - MYSQL_USER=projectzero
      - MYSQL_PASSWORD=projectzero