FROM openjdk:17-jdk-alpine

ENV SPRING_DATASOURCE_URL=jdbc:h2:file:~/database.db
ENV SPRING_DATASOURCE_USERNAME=projectzero
ENV SPRING_DATASOURCE_PASSWORD=projectzero
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=update
ENV JWT_ACCESS_TOKEN_SECRET=access_token_secret
ENV JWT_REFRESH_TOKEN_SECRET=refresh_token_secret
ENV JWT_TOKEN_SECRET=token_secret
ENV JWT_ACCESS_TOKEN_TTL_MINUTES=30
ENV JWT_REFRESH_TOKEN_TTL_DAYS=30

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]